---

- name: radicale is configured
  template:
    src: "{{item}}.j2"
    dest: "/etc/radicale/{{item}}"
    owner: root
    group: "{{ radicale_group }}"
    mode: 0750
  with_items:
    - logging
    - config
  notify: restart radicale

- name: systemd service is available
  template:
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/radicale.service"
    owner: root
    group: root
    mode: 0755
  notify:
    - reload systemd
    - restart radicale

- name: radicale is started and enabled at boot
  systemd:
    name: radicale
    state: started
    enabled: true
